### ISSUE TITLE
dgram.createSocket is not a function

### ISSUE THREAD

**Issue by kozlown** [krystianity/udpws#1]
Hi, I discovered that dgram was not implemented for browser, did you succeed to use udpws with a browser side client ? (if so, how ? )
Great job btw !

**Comment by krystianity** [comment]
Hi kozlown, I would love to help you on this topic - the problem with UDP in the browser are the missing APIs related to browser security issues. It is possible to write something hacky using WebRTCPeerConnection but that wont really do for something usefull.

I wrote this lib to have a replacement for "ws" or "uws" in my node projects that run server-side only, if you would want to use sockets to communicate from browser to server the best way would be to stick to TCP WebSockets for now.

I will maybe add the Hacky-Browser-UDP solution one day, or a working UDP-Browser-Client as soon as there is any solid API available.

Thanks.

**Comment by kozlown** [comment]
Yeah, that's what i saw too, but WebRTC looks complicated.. I'll keep using WebSocket.
Thx :)
